service:
  server:
    build: ./server
    container_name: online_compiler
    ports:
      - 8000:8000
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - server-node-modules:/app/node_modules

volumes:
  server-node-modules:
